import { useState, useEffect } from "react";
import api from "../api/axios";

/**
 * Career advice generated by the local LLM from the candidate's own skills and
 * the skills they are most often missing.
 *
 * Fetched separately from the rest of the dashboard: the first request costs a
 * few seconds of model time, so it must not delay anything else rendering.
 * Afterwards the backend serves a cached copy and the request is instant.
 */
function CareerTips() {
  const [tips, setTips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;

    const fetchTips = async () => {
      try {
        const res = await api.get("/recommendations/career-tips");
        if (!cancelled) setTips(res.data.ai_tips || []);
      } catch {
        if (!cancelled) setFailed(true);
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    fetchTips();
    return () => {
      cancelled = true;
    };
  }, []);

  // Nothing useful to show yet (no CV, or no matches to reason about) and
  // nothing went wrong — stay out of the way rather than showing an empty box.
  if (!loading && !failed && tips.length === 0) return null;

  return (
    <div className="mb-8">
      <div className="flex items-center justify-between gap-3 mb-4">
        <h3 className="font-serif text-lg text-ink">Career guidance</h3>
        <span className="text-sm text-slate">
          Based on your skills and the gaps in your applications
        </span>
      </div>

      {loading && (
        <div className="bg-white rounded-xl p-8 text-center border border-line">
          <p className="text-slate text-sm">Preparing your guidance...</p>
        </div>
      )}

      {failed && (
        <div className="bg-white rounded-xl p-6 border border-line">
          <p className="text-slate text-sm">
            Career guidance is unavailable right now. Your matches and
            applications are unaffected.
          </p>
        </div>
      )}

      {!loading && !failed && tips.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 sm:gap-4">
          {tips.map((tip, index) => (
            <div
              key={tip.title || index}
              className="bg-white rounded-xl p-5 border border-line"
            >
              <h4 className="font-medium text-ink mb-3">{tip.title}</h4>
              <ul className="space-y-2">
                {(tip.bullets || []).map((bullet, bulletIndex) => (
                  <li
                    key={bulletIndex}
                    className="text-sm text-slate flex gap-2"
                  >
                    <span className="text-indigo shrink-0">&bull;</span>
                    <span>{bullet}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default CareerTips;
